name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Workflow'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_IN_AUTOMATION: true
      IONOS_TOKEN: ${{ secrets.IONOS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

## Init tfstate from backend.tf file
      - name: Terraform Init
        run: terraform init -backend-config=backend.tf

## Plan the changes
      - name: Terraform Plan
        run: terraform plan

## Apply the changes
      - name: Terraform Apply
        run: terraform apply -auto-approve

